kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iscsi-target-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      release: "stable"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: iscsi-target
  name: iscsi-target
spec:
  containers:
    - name: target
      image: kubevirt/iscsi-target
      ports:
        - containerPort: 3260
      securityContext:
        privileged: true
        runAsUser: 0
      env:
      - name: FILE_SIZE
        value: "5G"
      - name: GENERATE_DEMO_OS_SEED
        value: 
      volumeMounts:
        - mountPath: /lib/modules
          name: modules
  volumes:
    - name: modules
      hostPath:
        path: /lib/modules
    - name: storage-claim
      persistentVolumeClaim:
        claimName: iscsi-target-claim
