language: generic
sudo: required
dist: trusty

services:
- docker

install:
- git reset --hard

script:
- export KUBEVIRT_UPDATE_CACHE_FROM="${TRAVIS_BRANCH}"
- export KUBEVIRT_CACHE_FROM="${TRAVIS_BRANCH}"
- if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then make pull-cache; fi # only use the cache in PRs, rebuild otherwise
- make generate
- if [[ -n "$(git status --porcelain)" ]] ; then echo "It seems like you need to run
  `make generate`. Please run it and commit the changes"; git status --porcelain; false; fi
- if diff <(git grep -c '') <(git grep -cI '') | egrep -v -e 'docs/.*\.png|swagger-ui' -e 'vendor/*' -e 'assets/*'
  | grep '^<'; then echo "Binary files are present in git repostory."; false; fi
- make build
- if [[ -n "$(git status --porcelain)" ]] ; then echo "It seems like you need to run
  `make`. Please run it and commit the changes"; git status --porcelain; false; fi
- if [[ $TRAVIS_REPO_SLUG == "kubevirt/kubevirt" ]]; then make goveralls; else make bazel-tests; fi
- make apidocs
- make client-python
- make manifests DOCKER_PREFIX="docker.io/kubevirt" DOCKER_TAG=$TRAVIS_TAG # skip getting old CSVs here (no QUAY_REPOSITORY), verification might fail because of stricter rules over time; falls back to latest if not on a tag
- make olm-verify

deploy:
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" && DOCKER_PREFIX="index.docker.io/kubevirt" DOCKER_TAG="latest" make bazel-push-images
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" && KUBEVIRT_UPDATE_CACHE_FROM="${TRAVIS_BRANCH}" make push-cache
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
    condition: $TRAVIS_BRANCH != revert-*
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" && DOCKER_PREFIX="index.docker.io/kubevirt"
    DOCKER_TAG="$TRAVIS_TAG" QUAY_REPOSITORY="kubevirt" PACKAGE_NAME="kubevirt-operatorhub"
    sh -c 'make bazel-push-images && make manifests && make olm-push'
  skip_cleanup: true
  file:
  on:
    tags: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: KD1d1EkvX5iY5pvKQbi6Aj6y49XXnQBxBMok9x2d9LVMbmzBQIHoTqUQz2Dv2TSpANshkIrLmR1eT/brCK382cIUVvA6kG8JB2yqAAE2hzJ8u49+CI4iyqpBWw1HCuH/4xPWZUPVBW0Yl9WsW0vencAeKK6cTDm4Z9K3esJf+iZMpJh7ZpK2ESn9d2RZsrpOKJpxYrvt14Wox+8YfqPRCTJoO/Q8vdXbyOrRVpK6daSe11HsmTZZpFzgLWGojpjH05wcENUaokpCIp8Hgx3rJmO9z5iReNG+2QuPCw0QyEIKGAvzlA5KbYFWBUurxz0XsnaovbJ7BKI070arxQKjKRnjSNE3kEValOwMIE8dA835A1nChm85NILQdWvlbexSxPpz0z62SGPjFthUj9VBx/RnUrd1itxWOi6ZW5k6PnWDUoKPr63+fYSAkp6bXO9ELexA19wUfQCicGRBEO3mJ6QvKKbiDAFKWcABlavxlNtFgw1mMPxxWEhKkW0PrCqOVu9fDDzJ48DCD5XHRT8HUVHDeKcscMTW675rlzo3SxTJdqnZSybpbMSmKbxNs0rM8kPXf1RQLsGDg4CC6Daxz255PV5Y/+p0AhZ2hWtfC3c/Ff8wOdDSdCaEcg5tGa/e1kJWAKuIATUGdZsFZUri8ePQcgcXzM4ihANn7gP8Cl4=
  file_glob: true
  file:
  - _out/cmd/virtctl/virtctl-*
  - _out/manifests/release/kubevirt.yaml
  - _out/templates/manifests/release/kubevirt.yaml.j2
  - _out/manifests/release/demo-content.yaml
  - _out/manifests/release/kubevirt-operator.yaml
  - _out/manifests/release/kubevirt-cr.yaml
  - _out/templates/manifests/release/kubevirt-operator.yaml.j2
  - _out/templates/manifests/release/kubevirt-cr.yaml.j2
  - _out/manifests/release/olm/kubevirt-operatorsource.yaml
  - _out/manifests/release/olm/bundle/kubevirtoperator.*.csv.yaml
  prerelease: true
  overwrite: true
  name: $TRAVIS_TAG
  on:
    tags: true
    repo: kubevirt/kubevirt
- provider: script
  skip_cleanup: true
  script: bash hack/gen-swagger-doc/deploy.sh
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: bash hack/gen-swagger-doc/deploy.sh
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: bash hack/gen-client-python/deploy.sh
  on:
    branch: master

env:
  global:
  # api-reference token
  - secure: pS1N+T7f20B9PJ2S6e4Bc0z0vK6wnUgtGrs1982iXYocVZZtL6LreXYV/9a5ANrykLx+/qeRxbR4FTknfJwsmm2MX1WN7FIEtp7wGxt5uU0Q+b5pERbgUL8amkvhc6Hj9eWn59fbEKSmAEeMupeYydPPCFJp8oumEEP6szb0zCj7LQPWxhEMtVLY2U8d3WbkhBoxC1Bv5kTOajaiyuwjgiJd3yvR6WfNOQUL167TCoyzRDoe7jUSZ9EScyDRg7mC2Nk2o4vzZwmaz8QjO6T6f2za95t7/kxhYrL7WAfa3POxdhHPP0XX4ZsypU6++hDj0txPAB/ICa55Za6A+BhFrUdGeoYb3T8jtWIF9UDHq6m8yhurtDPooR7VMjkR2ghz4Ol4cv2f1QWv5MGDg4hh9gKgjE+gbbeZyA5+t3l/Zf2HozZQCIDpMpi4EUUS3rCGkr44h0AjiZP9s4QrUY74kpT6GEGluFTlkXar+R3bvnTVY2J4vj6XGdAXHYtAbKI2/yaq20wqkbsC6BKHITcZ/E3eIBh2kc0WD4pdm8MnI0chuuMSkM6ynRDcPNYi235VmhxuUBaNWrkQEHGVOjXJPLB+xMRc6vVxAjV/OFaKXsbPb4aJl1TRJ1RclHAf4Am3SPuiowm8JmODTrmmYkF67rAGILO1oVxwmvwVLAmcJSI=
  # QUAY_USERNAME
  - secure: TDZ2IlrZOQGzZJoSigXeTzpiYCi93Vhy1uIvSFT1Co6C87x0rI57OTCY+5vZoD/l7EQT+q+kj2D+kFk/2gBoHhDA4k5iI+SgHdLhM3hgkrX0jGb72YTaQ8iJzBgLjF+z8DkCW6cze9THPH+HNQTwP9r2K3ptBOy5364eAiARCDqMf9gEMzsetoxR+2603f6ZEkUeDZCBT7e/wQy9kkC97NQ32GlEMCg3dk5xK2VHAqPL7Rbv58NDKrWDlfyRCRjL5RQmnuJTUwhX8awrDHAFjb4DUSMWPz7Xq/XyA1F7vD56Wpi2+ALnutdRrvO2dn3XuMkXBJpMEZXBsEorsLYB5UTUrYuWNO4RQIJIlth36kE7QmnnOb24PRjtNPLAzaTT6A1fr7rZAGmD2zINfPohym7JhuzmWWF1QXTo7Br45ASiEHExOZQfihRWhyvcpN9Iwl7PgbUkrp65M6XLfi6/YnAwY+sK2TYF3wn7eK8Lg9gUbxhnT42ANJui+00Gqm6mHtu+VqglMi98XxsicW/tiQO7hJ9A1uSGU9eJWG7M+6umCpvMyq1dTZ0gFSTnr8L1JzIyQnlea9jbcdrGeZsM+jQPOwE1bB6V7+s67j8qAJQRH8NBSWtCk8cb9UEpYZNdYwdvqaPFh07XXr8NXsx1iUqLZLa9CeqmeAzgGmMQFRY=
  # QUAY_PASSWORD
  - secure: b6mV6HECiehqEpInOG4iy++EQ/snKBSshCP/L9TjZ3vuBcnyd/ZR/ZMpcoR5515E1DHQtniI+KzyuJw2kzTHpaZVzXY6wuf/ti2/Dx4Pn5LXlZP9FOvdEXjuSOBo0YNR2Bf5jrjeJXnmTlmNBHdiOvkIMU9sy9ENKkJ8af6MzKFV+r3pVgH31bK61aRal/xkA/ccWgvM83XYxTUBP1kpT1Kwy1damG2yxRPgoNg3ErUml9NI9cIjNmH9sI1LPhAVTjAVMjJE9pFd5w4hysjrZlPxdEYx9p0KAZnmoRmhEhuLxmAXIohMKRtMNqWkq9DT5CnpV9yN1iBLYPoRlQ/1rK1nBPO41j+CyqcGDDRV6kNNxnFKgL/5hTQlI/BXnTR3CYJrMPyV2IbUKCV7agSS1VQzT6dphZT9G/e3J7IHONiKluwW/4JuoPYKC8IRmqOum0KVHIe8cdXMnHwNwFzl73t6LUrzge+ZbgdVmIudzRZ5lzolt33e6M0ODaGnO9lYgqW/fD7PjCebbV4t45I9336xrhT9x2NM7OejEtg2uXyQoOFn62VbcCrBhfdW2E9sY4TBYKn0RkpgzuRcxUrFmibzfpyjfeF/Da6DpBgNzvP/8u2MIwYrxHcCM98Y59E9JpnYvvXkGg3x2rcOX9dA5jg3a21giosi4Pv7uMxU7DQ=
  # DOCKER_USER
  - secure: B5ntCJhDBpheoILTHk1IKbLfbGPOTZBv00LVVhvRduHWhhMcYJtXBq5BkX75v/Gcedt3Mbnl7RA/QZ8pmMLWAQNr34almZTgWjLrJFnF310WpA7EIemHYUtveTLSej0BbWN692oQrYXUL3zuOHConowbl0RWVBFLSSzinIkiNekrmdXWJ/o6OQyWOOSgY25oUFIN6HdAqNbOfFvEUBXFMx2BmOzau86K+yiP70+9KJ9/n60QXopye30R0NEcgrgtxLe+/G60DMrljr6vBymAz8wTS51bXaiq1d5gmFAlgtuU2TbTDyltcjMnBGCQjKPX0Md1Dw7QrgpLSvLOQNgVBDOG5YGGyLF9qBEs9QcIVwv4E0OD1wYnfgpzKj1VuAwS+rUtBj4iXb53W/EkoHLST5WNkm6p+D7cJltjWRyNXx81Ti4f4jmq6/wrRApoHpqWlytNjbYjccISEoW0EmrEq59B3NPmAgGFztP3sbxmCOEk8eJcimh3HVjzNHyb9GzTJ+cnG+RuVl8+Ra02QQQnJqeyiBIsR3GA0NJNPQZcS3JX7GiRZLCT82Jpdv9jPXONLMycHlIdUhKh1jdM0LeeuzutaTVnlKmQ0JsFoBjFn8544sREv6KdAduFGgaGjGGtWxAYZiR6zi1mw/lTCr+8mYXbbiIsk6DU+48GNOy7M1w=
  # DOCKER_PASS
  - secure: R5GqRGRHc8LlWfrQO5bJYG++m33EHjtrBFjMunPIMwOuSE23j65SrC75VuhFLjNDgDALo0G+3Eu2p95eIiJsMlduamJ6MuML13owmeurbFg+hCoVdKCJIfkcRBPt1ie5UGwVZxhnZODul9eINi88lANufJFxT5s83fd5Rj+cNgCDbdqKVy9alry07ThULTvV5umoM1U0eqwEErCbpnEkDK3hWNAP46ropuLTsKMRe5Z3hZ1DRkNq2SkZMc0NC9fP76JUDY3vLnsF6c8u1tfWoX5cbgkz0+bSlX1eSrggteXPy8hNmVd4bJnBCocZElo7eL2I76xr+3lXsC4AJfFt4Wokgt2CcSjJiUs6MbgDiDip4JO4ch5La0Xtexj/JX1F9ncTCIAvOSfJTqwaeMIu7shywWg873BNviEBoxAogAsFqLldEbWwqTf4xg3LdFittj56BSoOYJqqWtUB5jz2iR6+0cnwdga5TYoRiea4Rawee4ytmrQF121gEm2kb5N3FRX6gckDXcqpTaKOw0OrrPbzssvhb5y6esdviha74ufwzb7kjoD/NgIkJzQBxmwAkG0BnV4H/K2CzJISiCypU+Svg1jE7Ya/UOE7+t7hbH7TNne7Vy2r0+UZufaOsT5spfCTfQsdn9ObKiE1q0+YttL3DWns5mprFZnjouJx9Xs=


notifications:
  irc:
    channels:
      - "chat.freenode.net#kubevirt"
    on_success: change
    on_failure: always
