apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstancePreset
metadata:
  creationTimestamp: null
  name: vmi-preset-virtiorng
spec:
  domain:
    devices: 
      rng:
        source: /dev/urandom
  selector:
    matchLabels:
      kubevirt.io/vmPreset: vmi-preset-virtiorng
