apiVersion: kubevirt.io/v1alpha1
kind: OfflineVirtualMachine
metadata:
  name: my-vm
  labels:
    my: label
spec:
  running: false # equivalent to replicas 0
  selector:
    matchLabels:
      my: label
  template:
    metadata:
      labels: 
        my: label
    spec:
      domain:
        resources:
          requests:
            memory: 8Mi
        devices:
          disks:
            - name: registrydisk
              volumeName: registryvolume
              disk:
                bus: virtio
      volumes:
        - name: registryvolume
          registryDisk:
            image: kubevirt/cirros-registry-disk-demo:devel
