apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachineReplicaSet
metadata:
  name: testreplicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      myvm: "myvm"
  template:
    metadata:
      name: test
      labels:
        myvm: "myvm"
    spec:
      domain:
        devices:
          graphics:
          - type: spice
          interfaces:
          - type: network
            source:
              network: default
          video:
          - type: qxl
          disks:
          - type: RegistryDisk:v1alpha
            source:
              name: kubevirt/cirros-registry-disk-demo:devel
            target:
              dev: vda
          - type: file
            target:
              dev: vdb
            cloudinit:
                nocloud:
                    userDataBase64: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogYXRvbWljCnNzaF9wd2F1dGg6IFRydWUKY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9Cg==
          consoles:
          - type: pty
        memory:
          unit: MB
          value: 64
        os:
          type:
            os: hvm
        type: qemu
