apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
metadata:
  name: atomic-ephemeral
spec:
  terminationGracePeriodSeconds: 0
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: registrydisk
        volumeName: registryvolume
        disk:
          dev: vda
      - name: cloudinitdisk
        volumeName: cloudinitvolume
        disk:
          dev: vdb
  volumes:
    - name: registryvolume
      registryDisk:
        image: kubevirt/fedora-atomic-registry-disk-demo:devel
    - name: cloudinitvolume
      cloudInitNoCloud:
        userDataBase64: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogYXRvbWljCnNzaF9wd2F1dGg6IFRydWUKY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9Cg==

