apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
metadata:
  name: testvm-sata
spec:
  terminationGracePeriodSeconds: 0
  domain:
    resources:
      requests:
        memory: 64M
    devices:
      disks:
      - name: mydisk
        volumeName: myvolume
        disk:
          bus: sata
  volumes:
    - name: myvolume
      iscsi:
        iqn: iqn.2017-01.io.kubevirt:sn.42
        lun: 2
        targetPortal: iscsi-demo-target.kube-system.svc.cluster.local
