apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
metadata:
  name: testvm-nocloud
spec:
  terminationGracePeriodSeconds: 5
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: registrydisk
        volumeName: registryvolume
        disk:
          bus: virtio
      - name: cloudinitdisk
        volumeName: cloudinitvolume
        disk:
          bus: virtio
  volumes:
    - name: registryvolume
      registryDisk:
        image: kubevirt/fedora-cloud-registry-disk-demo:devel
    - name: cloudinitvolume
      cloudInitNoCloud:
        userData: |
          #cloud-config
          password: fedora
          chpasswd: { expire: False }
          ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1ycGAtntmDCUz3H4UWSVv4LQ8L93bWxnyp test@test.com
