---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io: ""
  name: virtualmachineinstancemigrations.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: VirtualMachineInstanceMigration
    plural: virtualmachineinstancemigrations
    shortNames:
    - vmim
    - vmims
    singular: virtualmachineinstancemigration
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata: {}
        spec:
          properties:
            vmiName:
              type: string
        status:
          properties:
            phase:
              type: string
  version: v1alpha2
