swagger: '2.0'
info:
  title: virt-controller
  description: virt-controller
  version: "1.0.0"
host: localhost:8080
schemes:
  - http
basePath: /api/v1
produces:
  - application/json
paths:
  /domain/raw:
    post:
      summary: Post a domain XML here to start it somewhere in the cluster.
      description: |
        Post a domain XML here to start it somewhere in the cluster. Kubernetes will do the scheduling.
      consumes:
        - application/xml
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: The domain XML
          required: true
          schema:
            $ref: '#/definitions/domain'
      tags:
        - VM
      responses:
        201:
          description: VM defined
          schema:
            $ref: '#/definitions/v1.VM'
        400:
          description: Request is syntactically incorrect
        409:
          description: VM already exists

definitions:
  v1.VM:
    required:
      - name
      - uuid
    properties:
      name:
        type: string
      uuid:
        type: string
        format: uuid
  domain:
    required:
      - name
    properties:
      uuid:
        type: string
        format: uuid
      name:
        type: string
        format: string
