apiVersion: v1
kind: Pod
metadata:
  name: virt-launcher-{{.Domain}}
  labels:
    app: virt-launcher
    domain: {{.Domain}}
  annotations:
    domainXML: "{{.DomainXML}}"
spec:
  hostNetwork: true
  volumes:
  - name: var-lib-virt-qemu
    hostPath:
      path: /var/lib/libvirt/qemu
  - name: var-run-virt
    hostPath:
      path: /var/run/libvirt
  - name: var-domain-xml
    hostPath:
      path: /etc/vdsm/dom/
  - name: rhev-storage
    hostPath:
      path: /rhev/data-center/
  - name: podinfo
    downwardAPI:
      items:
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
  containers:
  - name: compute
    image: {{.DockerRegistry}}/{{.LauncherImage}}
    imagePullPolicy: IfNotPresent
    command:
        - "/virt-launcher"
        - "-downward-api-path"
        - "/etc/kubeapi/annotations"
    securityContext:
      privileged: true
    volumeMounts:
    - name: var-lib-virt-qemu
      mountPath: /var/lib/libvirt/qemu
    - name: var-run-virt
      mountPath: /var/run/libvirt
    - name: var-domain-xml
      mountPath: /etc/vdsm/dom/
    - name: rhev-storage
      mountPath: /rhev/data-center/
    - name: podinfo
      mountPath: /etc/kubeapi
{{if .NodeSelector}}  nodeSelector:
{{range $key, $value := .NodeSelector}}    {{$key}}: {{$value}}{{end}}{{end}}
