apiVersion: v1
kind: Service
metadata:
  name: iscsi-demo-target-tgtd
spec:
  ports:
    - name: iscsi
      port: 3260
      targetPort: 3260
  selector:
    name: iscsi-demo-target-tgtd
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: iscsi-demo-target-tgtd
  name: iscsi-demo-target-tgtd
spec:
  containers:
    - name: target
      image: fabiand/iscsi-target-tgtd
      ports:
        - containerPort: 3260
      env:
      - name: GENERATE_DEMO_OS_SEED
        value: "true"
